allprojects {
    repositories {
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/central" }
        maven { url "https://maven.aliyun.com/repository/public" }
        google()
        mavenCentral()
    }
    buildscript {
        repositories {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/central" }
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    buildscript {
        repositories {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/central" }
            maven { url "https://maven.aliyun.com/repository/public" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
}
subprojects { subproject ->
    subproject.afterEvaluate {
        def androidExt = subproject.extensions.findByName("android")
        if (androidExt != null) {
            androidExt.compileSdk = 36
        }
    }
    subproject.buildDir = "${rootProject.buildDir}/${subproject.name}"
    subproject.evaluationDependsOn(':app')
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
